query AllBookWhereName($user: String) {
  book_barter_books(where: { user: { _not: { name: { _eq: $user } } } }) {
    id
    title
    summary
    image_cover_url
    author
    user {
      name
      email
      phone_number
    }
  }
}
