query DetailBarterByUser($user: Int) {
  book_barter_details(where: { book: { user_id: { _eq: $user } } }) {
    id
    date
    alasan
    book {
      id
      title
    }
    user {
      name
      email
      phone_number
    }
    status
  }
}
