query DetailBarter($userId: Int) {
  book_barter_details(where: { peminjam_id: { _eq: $userId } }) {
    id
    date
    alasan
    book {
      id
      title
      user {
        name
      }
    }
    status
  }
}
